// <auto-generated />
using System;
using EFProject.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFProject.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20250316142545_InsDepartment-OneToMany")]
    partial class InsDepartmentOneToMany
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EFProject.Models.Course", b =>
                {
                    b.Property<Guid>("Crs_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Course_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("Dept_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Duration")
                        .HasColumnType("int");

                    b.Property<Guid?>("Ins_Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Crs_Id");

                    b.HasIndex("Dept_Id");

                    b.HasIndex("Ins_Id");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("EFProject.Models.CourseSession", b =>
                {
                    b.Property<Guid>("CrsSession_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Crs_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("Ins_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CrsSession_Id");

                    b.HasIndex("Crs_Id");

                    b.HasIndex("Ins_Id");

                    b.ToTable("CourseSessions");
                });

            modelBuilder.Entity("EFProject.Models.Department", b =>
                {
                    b.Property<Guid>("Dept_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Dept_Location")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Dept_Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Dept_Id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("EFProject.Models.Instructor", b =>
                {
                    b.Property<Guid>("Ins_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Dept_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Ins_Id");

                    b.HasIndex("Dept_id");

                    b.ToTable("Instructors");
                });

            modelBuilder.Entity("EFProject.Models.Course", b =>
                {
                    b.HasOne("EFProject.Models.Department", "Department")
                        .WithMany("Courses")
                        .HasForeignKey("Dept_Id");

                    b.HasOne("EFProject.Models.Instructor", "Instructors")
                        .WithMany("Courses")
                        .HasForeignKey("Ins_Id");

                    b.Navigation("Department");

                    b.Navigation("Instructors");
                });

            modelBuilder.Entity("EFProject.Models.CourseSession", b =>
                {
                    b.HasOne("EFProject.Models.Course", "Course")
                        .WithMany("CourseSessions")
                        .HasForeignKey("Crs_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFProject.Models.Instructor", "Instructor")
                        .WithMany("CourseSessions")
                        .HasForeignKey("Ins_Id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Course");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("EFProject.Models.Instructor", b =>
                {
                    b.HasOne("EFProject.Models.Department", "Department")
                        .WithMany("Instructors")
                        .HasForeignKey("Dept_id");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("EFProject.Models.Course", b =>
                {
                    b.Navigation("CourseSessions");
                });

            modelBuilder.Entity("EFProject.Models.Department", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("Instructors");
                });

            modelBuilder.Entity("EFProject.Models.Instructor", b =>
                {
                    b.Navigation("CourseSessions");

                    b.Navigation("Courses");
                });
#pragma warning restore 612, 618
        }
    }
}
